version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.7.7-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - /var/lib/rabbitmq
    env_file:
      - .env

  auth:
    build:
      context: ./
      dockerfile: ./apps/auth/Dockerfile
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: pnpm start:dev auth
    
    api:
      build:
        context: ./
        dockerfile: ./apps/api/Dockerfile
      env_file:
        - .env
      depends_on:
        - rabbitmq
        - auth
      volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
      command: pnpm start:dev api 

  postgres:
    image: postgres:11.2
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
  postgres_admin:
    image: dpage/pgadmin4
    container_name: postgres_admin
    depends_on:
      - postgres
    ports:
      - "15432:80"
    env_file:
      - .env

      